service:
  name: daily-signin

# Add the serverless-webpack plugin
plugins:
  - serverless-plugin-chrome

custom:
  chrome:
    flags:
      - --window-size=1280,1696 # Letter size
      - --hide-scrollbars

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  memorySize: 256
  region: ap-southeast-1
  # environment:
  # iamRoleStatements:
  #   - Effect: Allow
  #     Action:
  #       - "sns:Publish"
  #     Resource: "arn:aws:sns:*:*:lantouzi-bx"

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
