service:
  name: daily-signin

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  memorySize: 256
  region: ap-southeast-1
  timeout: 30
  # environment:
  # iamRoleStatements:
  #   - Effect: Allow
  #     Action:
  #       - "sns:Publish"
  #     Resource: "arn:aws:sns:*:*:lantouzi-bx"

functions:
  pgf:
    handler: handler.pgf
    environment:
      DEBUG: sls-chrome
    events:
      - http:
          method: get
          path: pgf
  debug:
    handler: handler.debug
    events:
      - http:
          method: get
          path: debug