service:
  name: aws-nodejs-typescript

# Add the serverless-webpack plugin
plugins:
  - serverless-plugin-chrome
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  memorySize: 256
  region: ap-southeast-1
  # environment:
  # iamRoleStatements:
  #   - Effect: Allow
  #     Action:
  #       - "sns:Publish"
  #     Resource: "arn:aws:sns:*:*:lantouzi-bx"

functions:
  debug:
    handler: handler.debug
    events:
      - http:
          method: get
          path: debug
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
